### ISSUE TITLE
4K and 8K video option?

### ISSUE THREAD

**Issue by deadman3000** [erkserkserks/h264ify#24]
I'd like to see support for higher resolutions please. Great addon though :)

**Comment by erkserkserks** [comment]
Can you post an example video?

**Comment by deadman3000** [comment]
http://www.youtube.com/watch?v=f0NdOE5GTgo

h264ify only goes up to 1440p

**Comment by erkserkserks** [comment]
I think this is due to Youtube dropping support for 4k H.264 video playback on the browser. Safari on OSX, which only supports H.264, can't play 4k videos on Youtube anymore: https://9to5mac.com/2017/01/12/youtube%E2%80%A4com-no-longer-supports-4k-video-playback-in-safari/

Interestingly, youtube-dl shows that a 4k H.264 version is available to download, so it may be possible to find a workaround.
`erks:~$ youtube-dl -F https://www.youtube.com/watch?v=f0NdOE5GTgo
[youtube] f0NdOE5GTgo: Downloading webpage
[youtube] f0NdOE5GTgo: Downloading video info webpage
[youtube] f0NdOE5GTgo: Extracting video information
[youtube] f0NdOE5GTgo: Downloading MPD manifest
[info] Available formats for f0NdOE5GTgo:
format code  extension  resolution note
249          webm       audio only DASH audio   56k , opus @ 50k, 1.95MiB
250          webm       audio only DASH audio   77k , opus @ 70k, 2.74MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 4.86MiB
171          webm       audio only DASH audio  129k , vorbis@128k, 4.26MiB
251          webm       audio only DASH audio  147k , opus @160k, 5.04MiB
278          webm       256x144    144p  104k , webm container, vp9, 30fps, video only, 3.36MiB
160          mp4        256x144    DASH video  122k , avc1.4d400c, 30fps, video only, 4.07MiB
242          webm       426x240    240p  239k , vp9, 30fps, video only, 6.40MiB
133          mp4        426x240    DASH video  280k , avc1.4d4015, 30fps, video only, 8.99MiB
243          webm       640x360    360p  448k , vp9, 30fps, video only, 12.08MiB
134          mp4        640x360    DASH video  529k , avc1.4d401e, 30fps, video only, 9.81MiB
244          webm       854x480    480p  824k , vp9, 30fps, video only, 21.33MiB
135          mp4        854x480    DASH video 1088k , avc1.4d401f, 30fps, video only, 19.99MiB
247          webm       1280x720   720p 1627k , vp9, 30fps, video only, 45.88MiB
136          mp4        1280x720   DASH video 1722k , avc1.4d401f, 30fps, video only, 38.43MiB
248          webm       1920x1080  1080p 2850k , vp9, 30fps, video only, 85.40MiB
137          mp4        1920x1080  DASH video 3153k , avc1.640028, 30fps, video only, 70.71MiB
264          mp4        2560x1440  DASH video 7705k , avc1.640032, 30fps, video only, 201.15MiB
271          webm       2560x1440  1440p 9183k , vp9, 30fps, video only, 253.14MiB
272          webm       7680x4320  4320p 15727k , vp9, 30fps, video only, 460.19MiB
266          mp4        3840x2160  DASH video 17778k , avc1.640033, 30fps, video only, 394.68MiB
313          webm       3840x2160  2160p 20957k , vp9, 30fps, video only, 584.66MiB
138          mp4        7680x4320  DASH video 78437k , avc1.640033, 30fps, video only, 1.85GiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)`

**Comment by erkserkserks** [comment]
Looks like Youtube has dropped support for 1440p and 4k h.264 streams altogether. ```youtube-dl -F``` no longer shows them at all.
