### ISSUE TITLE
problems with embed

### ISSUE THREAD

**Issue by raingart** [erkserkserks/h264ify#56]

**Comment by erkserkserks** [comment]
Could you post some reproduction steps? I wasn't able to reproduce the
console error when visiting that page.

**Comment by raingart** [comment]
@erkserkserks I posted a video. If the quality is bad then download
https://drive.google.com/open?id=1J-g4Hz-AFfr9daZgn0V9QFpG6lo56CQe

**Comment by erkserkserks** [comment]
Interesting. I wasn't able to reproduce on my machine, but after enabling the "Block third-party cookies and site data" setting, I was able to reproduce. https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

I'll see if I can find a better storage method or fallback so that it's robust against this type of failure.

**Comment by raingart** [comment]
> Block third-party cookies and site data

yes, is enabling, I did not think it to clarify, im sorry. It's amazing you guessed it.

> better storage method

I just tried `sessionsStorage` - and it failed too
`chrome.storage.sync` - it works, but a dubious way
there is another way, but it is very, very exotic (I found it in [violentmonkey](https://github.com/violentmonkey/violentmonkey)) - [Saving App Config To Google Drive](http://www.riskcompletefailure.com/2013/11/saving-app-config-to-google-drive.html)

I think that you can do without saving some of the settings. If someone installed and the more activated the extension, then the option - `Enable h264ify` and so must be activated (pre-enabled)

**Comment by sergeevabc** [comment]
FF 63.0.3 x64, h264ify 1.0.9 enabled
URL with Youtube video: https://www.reddit.com/r/videos/comments/a4zhe1/one_of_the_best_scenes_in_king_of_the_hill_hank/
Still loading VP9…

**Comment by Wsiegenthaler** [comment]
Reviving this because it's been really heating up my laptop every time I play embedded videos. The solution seems to be to just ditch `localStorage` and instead retrieve the options using the `storage.local` API and pass them into the injected script as a function parameter. I think the idea behind using `localStorage` was to prevent the player from querying `MediaSource` before the injection script had a chance to override it, but in all my experimenting I couldn't seem to produce this scenario.

I'll open a PR shortly with my proposed solution. It's been tested on current versions of Chrome and Firefox (77 and 71 respectively). I've also back checked it against Chromium 60 (old versions of Chrome are unavailable for download) and as far back as Firefox 55 without issue.

It'd be great if folks could test it themselves and report back, especially if you're running a slightly out-of-date browser. It's available in the master branch of my fork [here](https://github.com/wsiegenthaler/h264ify).
